#!/bin/bash

#VARS
DNS_SERVERS='8.8.8.8 8.8.4.4' # Add as many as you would like, separate with a space.
ROUTER='192.168.0.1' # The gateway that the cluster will use for internet access.
DOMAIN_NAME='cluser.domain.tld' # The FQDN of the cluster will use.
NTP_SERVER='192.168.0.1' # Address of the server that is running ntp for the nodes.
NEXT_SERVER='192.168.0.1' # Address of the server that will be used to PXE boot the nodes for cloning.
SUBNET='192.168.0.0' # Subnet the cluster network with use.
###############################################################################

apt-get -q update
apt-get -qy upgrade
cd /etc/dhcp3
wget --no-check-certificate https://github.com/jatkins/Charlie/raw/master/config/master/dhcpd.conf.temp
sed -i "s/_DNS_/$DNS_SERVERS/g" dhcpd.conf.temp
sed -i "s/_ROUTER_/$ROUTER/g" dhcpd.conf.temp
sed -i "s/_DOMAIN_NAME_/$DOMAIN_NAME/g" dhcpd.conf.temp
sed -i "s/_NTP_/$NTP_SERVERS/g" dhcpd.conf.temp
sed -i "s/_NEXT_/$NEXT_SERVER/g" dhcpd.conf.temp
sed -i "s/_SUBNET_/$SUBNET/g" dhcpd.conf.temp
mv dhcpd.conf.temp dhcpd.conf
apt-get -qy install nfs-common nfs-kernel-server dhcp3-server 

#slapd libnss-ldap libpam-ldap bind9
